export const ENV_FIELD_LABELS: Record<string, string> = {
  'groq.api_key': 'Groq API Key',
  'llm.llm_api_key': 'LLM API Key',
  'llm.llm_model': 'LLM Model',
  'llm.openai_base_url': 'LLM Base URL',
  'llm.ad_classifier_backend': 'Ad Classifier',
  'llm.jev_api_key': 'Jev API Key',
  'llm.jev_base_url': 'Jev Base URL',
  'llm.jev_model': 'Jev Model',
  'whisper.whisper_type': 'Whisper Mode',
  'whisper.api_key': 'Whisper API Key',
  'whisper.model': 'Whisper Model',
  'whisper.base_url': 'Whisper Base URL',
  'whisper.timeout_sec': 'Whisper Timeout (sec)',
  'whisper.chunksize_mb': 'Whisper Chunk Size (MB)',
  'whisper.max_retries': 'Whisper Max Retries',
};
